exports.validatorTypes = {
  THEME_MENTOR: 'theme-mentor',
  THEME_CHECK: 'theme-check'
}

exports.validatorLabels = {
  THEME_MENTOR: 'Theme Mentor for Themeforest',
  THEME_CHECK: 'Theme Check'
}

/* eslint-disable camelcase */
/* eslint-disable key-spacing */
exports.validatorThemeCheckLabels = {
  AdminMenu: 'Admin Menu',
  NoHiddenAdminBar: 'Admin Bar',
  Bad_Checks: 'Codes: Best Practice',
  Basic_Checks: 'Basic',
  CDNCheck: 'Content Delivery Network (CDN)',
  Comment_Reply: 'Comment Reply',
  CommentPaginationCheck: 'Comment Pagination',
  Constants: 'Codes: Best Practice',
  ContentWidthCheck: 'Theme Feature: Content Width',
  CustomizerCheck: 'Theme Feature: Customizer',
  CustomCheck: 'Theme Feature: Basic',
  Deprecated_Recommended: 'Codes: Deprecated',
  Deprecated: 'Codes: Deprecated',
  DeregisterCheck: 'Codes: De-register Script',
  DirectoriesCheck: 'File Structure: Hidden Directory',
  EditorStyleCheck: 'Theme Feature: Editor Style',
  FaviconCheck: 'Theme Feature: Favicon',
  File_Checks: 'File Structure: File Extension',
  GeneratedCheck: 'Codes: Generated by Framework',
  GravatarCheck: 'Theme Feature: Gravatar',
  I18NCheck: 'Translation: Internationalization',
  IframeCheck:'Codes: Iframe',
  IncludeCheck: 'Codes: Best Practice',
  IncludedPlugins: 'File Structure: File Extension',
  LineEndingsCheck: 'Codes: Line Endings',
  Check_Links: 'Codes: Links',
  MalwareCheck: 'Security: Malware',
  More_Deprecated: 'Codes: Deprecated',
  NavMenuCheck: 'Theme Feature: Nav Menu',
  NonPrintableCheck: 'Codes: Unknown Characters',
  PHPShortTagsCheck: 'Codes: Best Practice',
  Plugin_Territory: 'Codes: Theme Best Pactice',
  PostFormatCheck: 'Theme Feature: Post Formats',
  PostPaginationCheck: 'Theme Feature: Post Pagination',
  PostThumbnailCheck: 'Theme Feature: Post Thumbnail',
  Screenshot_Checks: 'File Structure: Screenshot',
  SearchFormCheck: 'Theme Feature: Search Form',
  Style_Needed: 'Codes: Important Styles',
  Style_Suggested: 'Codes: Recommended Styles',
  Style_Tags: 'Codes: Best Practice',
  TagCheck: 'Theme Feature: Tags',
  TextDomainCheck: 'Codes: Text Domain',
  Time_Date: 'Codes: Time and Date',
  Title_Checks: 'Codes: Best Practice',
  Check_URI: 'Codes: Best Practice',
  WidgetsCheck: 'Theme Feature: Widgets',
  WormCheck: 'Security: Worm'
}
/* eslint-enable */
